---

- name: 00-playbook  # Completing part 1.1 of the task
  ansible.builtin.import_playbook: inc/00-playbook.yml

- name: 01-playbook  # Completing part 1.2 of the task
  ansible.builtin.import_playbook: inc/01-playbook.yml

- name: 02-playbook  # Completing part 1.3 of the task
  ansible.builtin.import_playbook: inc/02-playbook.yml
