---
- name: 02-playbook  # Completing part 1.3 of the task
  hosts: all
  vars:
    welcome_message: "Welcome to SYSTEM!!!"    

  tasks: 
    # Change a MOTD 
    - name: Change a MOTD
      ansible.builtin.lineinfile:
        path: /etc/update-motd.d/01-header-custom
        line: printf "{{ welcome_message  }}"

